openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts API
  license:
    name: Apache 2.0
    url: <http://www.apache.org/licenses/LICENSE-2.0.html>
  description: >
    API for user contact management
tags:
  - name: Auth
    description: Operations about auth
  - name: Contacts
    description: Operations about contacts
servers:
  - url: https://nodejs-hw-mongodb-nls0.onrender.com
  - url: localhost:3000
paths:
  /auth/register:
    post:
      $ref: '../swagger/paths/auth/register.yaml'
  /auth/login:
    post:
      $ref: '../swagger/paths/auth/login.yaml'
  /auth/refresh:
    post:
      $ref: '../swagger/paths/auth/refresh.yaml'
  /auth/send-reset-email:
    post:
      $ref: '../swagger/paths/auth/send-reset-email.yaml'
  /auth/reset-pwd:
    post:
      $ref: '../swagger/paths/auth/reset-pwd.yaml'
  /auth/logout:
    post:
      $ref: '../swagger/paths/auth/logout.yaml'
  /contacts:
    post:
      $ref: '../swagger/paths/contacts/create-contact.yaml'
    get:
      $ref: ../swagger/paths/contacts/get-contacts.yaml
  /contacts/{contactId}:
    get:
      $ref: ../swagger/paths/contacts/{id}/get-contact-by-id.yaml
    patch:
      $ref: ../swagger/paths/contacts/{id}/update-contact.yaml
    delete:
      $ref: ../swagger/paths/contacts/{id}/delete-contact.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
